#!/bin/sh

[ -e /etc/ssh/ssh_host_ecdsa_key ]           && cp /etc/ssh/ssh_host_ecdsa_key            /var/backups/ssh_host_ecdsa_key
[ -e /etc/ssh/ssh_host_ecdsa_key.pub ]       && cp /etc/ssh/ssh_host_ecdsa_key.pub        /var/backups/ssh_host_ecdsa_key.pub
[ -e /etc/ssh/ssh_host_ed25519_key ]         && cp /etc/ssh/ssh_host_ed25519_key          /var/backups/ssh_host_ed25519_key
[ -e /etc/ssh/ssh_host_ed25519_key.pub ]     && cp /etc/ssh/ssh_host_ed25519_key.pub      /var/backups/ssh_host_ed25519_key.pub
[ -e /etc/ssh/ssh_host_rsa_key ]             && cp /etc/ssh/ssh_host_rsa_key              /var/backups/ssh_host_rsa_key
[ -e /etc/ssh/ssh_host_rsa_key.pub ]         && cp /etc/ssh/ssh_host_rsa_key.pub          /var/backups/ssh_host_rsa_key.pub

account backup
